### ISSUE TITLE
No temperature compensation of the EC

### ISSUE THREAD

**Issue by danielfppps** [kromadg/soil-sensor#1]
According to the code, the soil_ec value remains the same regardless of the temperature. According to the Teros 12 manual, the soil_ec is temperature corrected using:

soil_ec = soil_ec/(1.0f+0.019f*(soil_temp-25.0f));

Is there any reason why you have not performed a temperature correction of the read EC?

**Comment by kromadg** [comment]
Hey Daniel!

Thanks for the review.

There's a temperature compensation in [soil_pore_permittivity calculation](https://github.com/kromadg/soil-sensor/blob/main/soil_sensor.ino#L66), as in Hilhorst 2000 paper.

I did it that way because according to the manufacturer at the time I acquired the CWT sensors, there was already temperature compensation in the substrate EC measurement. But now I can't find references to it anymore (besides, it's not common in TDR-type sensors, so I may have been wrong).

I will try to make a temperature compensation on this calibration as per your recommendation.
