### ISSUE TITLE
For low EC values, correction gives increasingly negative bulk EC values

### ISSUE THREAD

**Issue by danielfppps** [kromadg/soil-sensor#3]
The equation suggested gives negative values below around 250 uS/cm.

![image](https://user-images.githubusercontent.com/10372058/212485945-06cca0c6-2b72-4615-92ce-d89b563001e7.png)

This causes my sensor to give negative readings a large percentage of the time for bulk EC and pore EC values. I would suggest calibration points to include solutions with EC of 0 (distilled water) in media that has no conductivity contribution (rockwool for example) to avoid this problem.

**Comment by kromadg** [comment]
For sure. I even had/have plans to make a calibration manual with 4 or 5 formulas with different EC (0.25, 0.5, 0.75, 1) to have more reliable calibration points. Since my data is limited to a few EC ranges from a pot with a real plant.

**Comment by kromadg** [comment]
I bought more THC-S sensors and I found that's not a very realiable sensor since the measured bulk EC varies between sensors in the same substrate.

Maybe create a method and a simple calc app to solve this:

- Create calibration solutions with EC 0.25, 0.5, 0.75, 1 measured with a Teros, Acclima or another reliable sensor.
- A user at his house will create the calibration solutions and will know the difference between his sensor and the one measured by that realiable sensor.
- He throws his measurements into the calculator app and see what's the cubic polynomial for example he needs to use on his arduino to correct the bulk EC.

**Comment by danielfppps** [comment]
I've been doing some experimentation. The method that has worked best, which I think is simplest, is to do a linear calibration of the bulk ec with distilled water (~0 mS/cm) and a solution in the 1-1.5mS/cm range. I got this equation for the bulk_ec for both of my sensors using this method:

soil_ec = 1.93 * soil_ec - 270.8;
soil_ec = soil_ec / (1.0 + 0.019 * (soil_temp - 25));

Then the rest of the equations you used for the pore EC seem to be working fine.

**Comment by kromadg** [comment]
> I've been doing some experimentation. The method that has worked best, which I think is simplest, is to do a linear calibration of the bulk ec with distilled water (~0 mS/cm) and a solution in the 1-1.5mS/cm range. I got this equation for the bulk_ec for both of my sensors using this method:
> 
> soil_ec = 1.93 * soil_ec - 270.8; soil_ec = soil_ec / (1.0 + 0.019 * (soil_temp - 25));
> 
> Then the rest of the equations you used for the pore EC seem to be working fine.

Great! Thanks for the support Daniel. I will update the code with your changes.
